name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: Install Flet
        run: pip install flet==0.21.2
      - name: Build APK
        run: flet build apk --project "SINDBAD_OBD" --org "com.sindbad.pro"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SINDBAD-PRO-INSTALL
          path: build/apk/*.apk
